DELETE http://localhost:3001/api/blogs/67c70f07ab97e29d4af5f612
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt1c2giLCJpZCI6IjY3YzZkNjI3YWNiNTFlOThiYWJjNjE3ZSIsImlhdCI6MTc0MTA5OTA0MSwiZXhwIjoxNzQxMDk5MzQxfQ.6erE1Uhw7-k9oZV_eze8wsgMNJAVSDWqLdzh11vlYJU